name: Andrew Price Photography
favicon: null
layout_spectrum: 0.2484145585913211
typography_spectrum: 0.8942715963348746
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e9ecf1'
    - '#304a00'
    - '#ffd43e'
    - '#918d95'
    - '#6b0031'
  brandStrength: 0.5146797921042889
  lightness: 0.9075851747766137
  saturation: 0.7641905583441257
  rhythmicContrast: 0.33242017356678843
purpose: []
